on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
      - name: Build
        run: |
          git clone https://github.com/dani-garcia/bitwarden_rs.git
          cd bitwarden_rs && cargo build --features sqlite --release
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: bitwarden_rs
          path: bitwarden_rs/target/release/bitwarden_rs
